name = "ContingencyTables"
uuid = "d8605af1-a39a-40e5-82f3-4793871169cd"
authors = ["Yanwen Wang <yanwenwang@u.nus.edu>"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CategoricalArrays = "0.10.8"
DataAPI = "1.16.0"
DataFrames = "1.7.0"
julia = "1.0"
